name: Cypress UI Test

# Triggers the workflow on any push or pull request to all branches
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3


      # Install NPM dependencies (including Cypress)
      - name: Install dependencies
        run: npm ci

      # Start your web application (if applicable) 
      # (replace with your actual start command if needed)
      - name: Start the application
        run: npm run start &
      
      # Wait for the application to start up before running tests
      - name: Wait for application to start
        run: npx wait-on http://localhost:3000

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run

      # Upload screenshots and videos as artifacts if tests fail (optional)
      - name: Upload Cypress artifacts (screenshots/videos)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/screenshots/

      # Upload test results as artifacts (optional)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results/

