name: ZAP Baseline Scan
permissions:
  issues: write


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap-scan:
    name: ZAP Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com/?response_type=code&client_id=bue83b3b34&redirect_uri=https%3A%2F%2Foauth.pstmn.io%2Fv1%2Fcallback'
