name: CI Test Workflow

# Trigger the workflow on push or pull request to any branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16] # You can test across different Node.js versions

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

      # Optionally, upload test reports or coverage reports as artifacts
      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: ./test-reports
